// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "../lvgl/lvgl.h"

#include "ui_events.h"
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1524113965);    // assets\MHW-Nergigante_Icon.png




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
